package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.32

import (
	"context"
	"strconv"

	"github.com/surasithaof/gin-graphql-server/graph/loader"
	"github.com/surasithaof/gin-graphql-server/graph/model"
	playerModel "github.com/surasithaof/gin-graphql-server/players/model"
	teamModel "github.com/surasithaof/gin-graphql-server/teams/model"
)

// CreateTeam is the resolver for the createTeam field.
func (r *mutationResolver) CreateTeam(ctx context.Context, input model.TeamInput) (*model.Team, error) {
	newTeam := &teamModel.Team{
		Name:    input.Name,
		Country: input.Country,
	}
	team, err := r.TeamStore.Create(ctx, newTeam)
	if err != nil {
		return nil, err
	}
	return &model.Team{
		ID:      strconv.Itoa(team.ID),
		Name:    team.Name,
		Country: team.Country,
	}, nil
}

// UpdateTeam is the resolver for the updateTeam field.
func (r *mutationResolver) UpdateTeam(ctx context.Context, id string, input model.TeamInput) (*model.Team, error) {
	updateTeam := &teamModel.Team{
		Name:    input.Name,
		Country: input.Country,
	}
	_id, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}
	team, err := r.TeamStore.Update(ctx, _id, updateTeam)
	if err != nil {
		return nil, err
	}
	return &model.Team{
		ID:      strconv.Itoa(team.ID),
		Name:    team.Name,
		Country: team.Country,
	}, nil
}

// DeleteTeam is the resolver for the deleteTeam field.
func (r *mutationResolver) DeleteTeam(ctx context.Context, id string) (bool, error) {
	_id, err := strconv.Atoi(id)
	if err != nil {
		return false, err
	}
	err = r.TeamStore.Delete(ctx, _id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// CreatePlayer is the resolver for the createPlayer field.
func (r *mutationResolver) CreatePlayer(ctx context.Context, input model.PlayerInput) (*model.Player, error) {
	teamId, err := strconv.Atoi(input.TeamID)
	if err != nil {
		return nil, err
	}

	newPlayer := &playerModel.Player{
		Name:   input.Name,
		Rating: input.Rating,
		TeamID: teamId,
	}
	player, err := r.PlayerStore.Create(ctx, newPlayer)
	if err != nil {
		return nil, err
	}
	return &model.Player{
		ID:     strconv.Itoa(player.ID),
		Name:   player.Name,
		Rating: player.Rating,
		TeamID: strconv.Itoa(teamId),
	}, nil
}

// UpdatePlayer is the resolver for the updatePlayer field.
func (r *mutationResolver) UpdatePlayer(ctx context.Context, id string, input model.PlayerInput) (*model.Player, error) {
	_id, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}
	teamId, err := strconv.Atoi(input.TeamID)
	if err != nil {
		return nil, err
	}

	updatePlayer := &playerModel.Player{
		Name:   input.Name,
		Rating: input.Rating,
		TeamID: teamId,
	}
	player, err := r.PlayerStore.Update(ctx, _id, updatePlayer)
	if err != nil {
		return nil, err
	}
	return &model.Player{
		ID:     strconv.Itoa(player.ID),
		Name:   player.Name,
		Rating: player.Rating,
		TeamID: strconv.Itoa(teamId),
	}, nil
}

// DeletePlayer is the resolver for the deletePlayer field.
func (r *mutationResolver) DeletePlayer(ctx context.Context, id string) (bool, error) {
	_id, err := strconv.Atoi(id)
	if err != nil {
		return false, err
	}
	err = r.PlayerStore.Delete(ctx, _id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// Team is the resolver for the team field.
func (r *playerResolver) Team(ctx context.Context, obj *model.Player) (*model.Team, error) {
	team, err := loader.LoadTeam(ctx, obj.TeamID)
	if err != nil {
		return nil, err
	}
	return &model.Team{
		ID:      strconv.Itoa(team.ID),
		Name:    team.Name,
		Country: team.Country,
	}, nil
}

// Team is the resolver for the team field.
func (r *queryResolver) Team(ctx context.Context, id string) (*model.Team, error) {
	team, err := loader.LoadTeam(ctx, id)
	if err != nil {
		return nil, err
	}

	return &model.Team{
		ID:      strconv.Itoa(team.ID),
		Name:    team.Name,
		Country: team.Country,
	}, nil
}

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context) ([]*model.Team, error) {
	teams, err := r.TeamStore.FindAll(ctx)
	if err != nil {
		return nil, err
	}
	teamsRes := []*model.Team{}
	for _, t := range teams {
		teamsRes = append(teamsRes, &model.Team{
			ID:      strconv.Itoa(t.ID),
			Name:    t.Name,
			Country: t.Country,
		})
	}
	return teamsRes, nil
}

// Player is the resolver for the player field.
func (r *queryResolver) Player(ctx context.Context, id string) (*model.Player, error) {
	player, err := loader.LoadPlayer(ctx, id)

	if err != nil {
		return nil, err
	}

	team, err := loader.LoadTeam(ctx, strconv.Itoa(player.TeamID))
	if err != nil {
		return nil, err
	}
	return &model.Player{
		ID:     strconv.Itoa(player.ID),
		Name:   player.Name,
		Rating: player.Rating,
		TeamID: strconv.Itoa(team.ID),
		Team: &model.Team{
			ID:      strconv.Itoa(team.ID),
			Name:    team.Name,
			Country: team.Country,
		},
	}, nil
}

// Players is the resolver for the players field.
func (r *queryResolver) Players(ctx context.Context) ([]*model.Player, error) {
	players, err := r.PlayerStore.FindAll(ctx)
	if err != nil {
		return nil, err
	}
	playersRes := []*model.Player{}
	for _, p := range players {
		team, err := loader.LoadTeam(ctx, strconv.Itoa(p.TeamID))
		if err != nil {
			return nil, err
		}
		playersRes = append(playersRes, &model.Player{
			ID:     strconv.Itoa(p.ID),
			Name:   p.Name,
			Rating: p.Rating,
			TeamID: strconv.Itoa(team.ID),

			Team: &model.Team{
				ID:      strconv.Itoa(team.ID),
				Name:    team.Name,
				Country: team.Country,
			},
		})
	}
	return playersRes, nil
}

// Players is the resolver for the players field.
func (r *teamResolver) Players(ctx context.Context, obj *model.Team) ([]*model.Player, error) {
	teamId, err := strconv.Atoi(obj.ID)
	if err != nil {
		return nil, err
	}
	players, err := r.PlayerStore.FindByTeamId(ctx, teamId)
	if err != nil {
		return nil, err
	}
	teamPlayers := []*model.Player{}
	for _, p := range players {
		player, err := loader.LoadPlayer(ctx, strconv.Itoa(p.ID))
		if err != nil {
			return nil, err
		}
		teamPlayers = append(teamPlayers, &model.Player{
			ID:     strconv.Itoa(player.ID),
			Name:   player.Name,
			Rating: player.Rating,
			TeamID: strconv.Itoa(teamId),
		})
	}

	return teamPlayers, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Player returns PlayerResolver implementation.
func (r *Resolver) Player() PlayerResolver { return &playerResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Team returns TeamResolver implementation.
func (r *Resolver) Team() TeamResolver { return &teamResolver{r} }

type mutationResolver struct{ *Resolver }
type playerResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type teamResolver struct{ *Resolver }
