// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Player struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Rating float64 `json:"rating"`
	Team   *Team   `json:"team"`
}

type PlayerInput struct {
	Name   string  `json:"name"`
	Rating float64 `json:"rating"`
	TeamID string  `json:"teamId"`
}

type Team struct {
	ID      string    `json:"id"`
	Name    string    `json:"name"`
	Country string    `json:"country"`
	Players []*Player `json:"players"`
}

type TeamInput struct {
	Name    string `json:"name"`
	Country string `json:"country"`
}
